version: 0.0
os: ubuntu
files:
  - source: /
    destination: /var/www/html

hooks:
  BeforeInstall:
    - location: script/install.sh
      timeout: 500
      runas: root


  ApplicationStop:
    - location: script/stop.sh
      timeout: 300
      runas: root


  ApplicationStart:
    - location: script.sh/start.sh
      timeout: 300
      runas: root

