version: 0.2

run-as: root

env:
  parameter-store:
            DB_PASSWORD: "/DB_PASSWORD"

phases:
   pre_build:
     commands:
       - echo "Pre build step executing"
       - apt update -y
       - echo "Installing Nginx and php"
       - apt install nginx -y
       - apt install php php-fpm -y
       - echo "Installed pre_build commands"

   build:
     commands:
        - sed -i 's/password_here/'$DB_PASSWORD'/' wp-config.php
        - prientenv

artifacts:
  files:
    - echo "Upload artifact to bucket for deploy"
    - '**/*'


